// <auto-generated />
namespace Platinum.Life.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Removekakfrombank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removekakfrombank));
        
        string IMigrationMetadata.Id
        {
            get { return "202201280235474_Remove kak from bank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
